
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - demo_vendor:/var/www/html/vendor
      - demo_node_modules:/var/www/html/node_modules
      - demo_storage:/var/www/html/storage
    depends_on:
      - db

  web:
    image: nginx:1.25-alpine
    container_name: demo-web
    restart: unless-stopped
    ports:
      - "6162:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: demo-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: secret
    command: --default-authentication-plugin=caching_sha2_password
    volumes:
      - demo_db:/var/lib/mysql
    ports:
      - "3306:3306"

  mailpit:
    image: axllent/mailpit:latest
    container_name: demo-mail
    restart: unless-stopped
    ports:
      - "8025:8025"
    environment:
      MP_MAX_MESSAGES: 10000

  node:
    image: node:20-alpine
    container_name: demo-node
    working_dir: /var/www/html
    restart: unless-stopped
    volumes:
        - ./:/var/www/html
        - demo_node_modules:/var/www/html/node_modules
    depends_on:
        - app
    command: sh -c "npm ci || npm install && tail -f /dev/null"

volumes:
  demo_db:
  demo_vendor:
  demo_node_modules:
  demo_storage:
